# Generated by Django 3.1.5 on 2021-05-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0003_personalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
